# The URL the site will be built for
title = "Daniel Bodnar"
description = "Daniel Bodnar | Platform Engineer • Systems Architect • Linux Evangelist • Emerging Technologist"
base_url = "https://bodnar.sh"

# Use base_url present below if deploying using GitHub Pages
# base_url = "https://danielbodnar.github.io/bodnar-resume"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Personal Information
name = "Daniel Bodnar"
job_title = "Platform Engineer • Systems Architect • Linux Evangelist • Emerging Technologist"
bio = """I bring three decades of cross-domain expertise spanning the entire software engineering ecosystem, from low-level systems programming and infrastructure automation to application development and enterprise architecture. This breadth enables me to identify solutions and optimize systems in ways that specialists confined to a single domain cannot. I thrive in high-pace, rapidly evolving environments that require continual learning and absorbing large amounts of information, and really enjoy identifying abstract connections."""
email = "daniel@bodnar.sh"
phone = "(940) 247-0019"
location = "Denton, Texas"
website = "https://bodnar.sh"
github = "https://github.com/danielbodnar"
profile_pic = "/images/profilepic.jpg"
resume_pdf = "/danielbodnar.resume.pdf"

# Professional Profile
[[extra.profile_statements]]
title = "Problem Statement"
content = "The industry is saturated with specialists who have followed predictable career trajectories, creating a shortage of engineers who can bridge multiple technical domains. Organizations consistently struggle to find professionals who understand both the granular technical details and the broader architectural implications across traditionally siloed disciplines."

[[extra.profile_statements]]
title = "Value Proposition"
content = "I bring three decades of cross-domain expertise spanning the entire software engineering ecosystem, from low-level systems programming and infrastructure automation to application development and enterprise architecture. This breadth enables me to identify solutions and optimize systems in ways that specialists confined to a single domain cannot. I thrive in high-pace, rapidly evolving environments that require continual learning and absorbing large amounts of information, and really enjoy identifying abstract connections. This has served me well in time-sensitive, high-pressure situations where understanding the underlying root cause quickly can mean the difference between a minor incident and a major outage."

quote = "In my experience, in order to truly know what a tool does well, you must first understand what it does not do well."

philosophy = "I thrive on complex challenges and novel problems but struggle with monotonous maintenance work. I'm probably not the best tool for the job if you're looking for someone to maintain and operate stable, predictable systems without innovation or evolution... though I would love to build them for you."

# Early Career Highlights
[[extra.early_career]]
content = "Built my first website at 11, on a legal pad...in my bathroom... four years after the birth of the Internet. Two years later, we got dial up."

[[extra.early_career]]
content = "At 17 I was writing HL7 (medical data exchange) protocols, and modified/supported data entry systems built in MS DOS-based FoxPro 2.1"

[[extra.early_career]]
content = "At 19 I accepted a position as Windows Network Administration/SysAdmin of a small office, solely responsible for 2 domain controllers (2000, 2003), 11 work stations, and a checkpoint firewall. Fun fact: I renamed the domain admin username to \"Deoxyribonucleic\" for \"security\" reasons"

[[extra.early_career]]
content = "Launched and ran a computer repair and IT Consulting company for five years (managing up to five employees at one point) named TACC Support (Technicians Against Computer Cruelty)"

# Work Experience
[[extra.experience]]
title = "Founder, Cloud Architect, CIO"
company = "BitBuilder Cloud, LLC"
location = "Dallas, Texas"
start_date = "2021"
end_date = "Present"
description = "Launched a Cloud Hosting and Consulting private SaaS company with a focus on providing a vendor-agnostic, e2e encrypted, highly-available, and globally distributed hyper-converged platform for cost-efficient resiliency against hostile attackers."
achievements = [
    "Single-handedly built core services on co-located custom bare metal servers with over 2TB RAM, 320 cores, 64TB NVMe storage",
    "Containerized and load-balanced several high-profile organizations with 1M+ global visitors/day",
    "Orchestrated global scaling via multi-cloud hybrid overlay layer based on custom k8s distribution and immutable Linux systems",
    "Implemented constant monitoring and observability using Grafana, Prometheus, VictoriaMetrics, NetData, and Jaeger"
]

[[extra.experience]]
title = "Principal Software, DevOps, and Cloud Engineer"
company = "Fidelity Investments"
location = "SouthLake, TX"
start_date = "2023"
end_date = "2025"
description = "Served as a technical leader and cloud architect, designing and implementing enterprise-scale cloud solutions while mentoring teams on AWS best practices and modern DevOps methodologies."
achievements = [
    "Architected comprehensive AWS solutions for enterprise applications, including designing secure networking topologies and multi-account strategies",
    "Developed and implemented robust IAM policies and CloudFormation templates adhering to strict financial industry security standards",
    "Designed and built a full AWS CDK platform enabling teams to rapidly deploy standardized, compliant infrastructure",
    "Engineered Kubernetes-based deployment solutions leveraging EKS, Helm charts, and custom operators for application management",
    "Rebuilt and optimized the Jenkins Core platform, increasing build efficiency and reducing pipeline execution times",
    "Created a cloud orchestration CLI tool that simplified cross-account resource management and deployment workflows",
    "Successfully deployed and managed Discourse forums on Alpine Linux containers in Kubernetes, ensuring high availability and performance",
    "Implemented infrastructure-as-code practices across multiple teams, significantly reducing configuration drift and deployment errors",
    "Designed and implemented automated security scanning and compliance checking within CI/CD pipelines",
    "Led knowledge-sharing sessions and developed documentation to elevate team capabilities in cloud-native technologies"
]

[[extra.experience]]
title = "SRE, SysAdmin, and Platforms Engineer"
company = "RSVP & ACT, Inc"
location = "Denton, TX"
start_date = "2019"
end_date = "2021"
achievements = [
    "Managed and performance-tuned +3.5TB PostgreSQL database cluster, MySQL and SQLite databases",
    "Architected, deployed, and managed dynamically scaling, secure, and fully version-controlled hybrid and bare-metal Kubernetes clusters",
    "Deployed and managed self-hosted GitLab instance with DevOps build pipelines and automatic blue-green deployments",
    "Implemented monitoring, alerting, logging, tracing, and observability tools",
    "Implemented and enforced GitLab-based Infrastructure-as-Code procedures and pipelines",
    "Deployed and managed multiple host, network, and container security tools and vulnerability scanners",
    "Simplified and standardized hypervisors with a centralized Proxmox cluster on ZFS and a 56G InfiniBand FC SAN",
    "Deployed W2019 AD server environment for centralized user account management",
    "Implemented organization-wide VPN, VLANs, and security measures",
    "Provided training to address knowledge-gaps and mitigated ransomware hacks"
]

[[extra.experience]]
title = "IT Director"
company = "Perspectives.org"
location = "Pasadena, CA"
start_date = "2017"
end_date = "2019"
achievements = [
    "Led the IT team and support department as well as India based dev. team to support existing infrastructure while developing a 5 year vision roadmap to rebuild legacy monolithic .NET 3.5 application into 18 modern department and role-based portals",
    "Increased cloud hosting capacity by 10x while reducing budget by 50%",
    "Reduced minimum page load time from 5 seconds to an average of 0.8 seconds",
    "Built a DRM-secured offline-enabled streaming video player desktop app in Go"
]

[[extra.experience]]
title = "Professional Application Developer"
company = "AT&T Corp."
location = "Plano, TX"
start_date = "2014"
end_date = "2017"
achievements = [
    "Full stack application engineer building custom web-based tools and services for enterprise operations",
    "Managed entire project pipeline, from requirements gathering to production deployment",
    "Led team-wide migration from Rails/MySQL stack to Node.js, Angular.js, and MongoDB",
    "Engineered a Docker-based DevOps and deployment pipeline for microservices architecture"
]

# Skills
[[extra.skills]]
name = "Kubernetes"
level = 95

[[extra.skills]]
name = "Docker"
level = 95

[[extra.skills]]
name = "AWS"
level = 90

[[extra.skills]]
name = "Linux"
level = 95

[[extra.skills]]
name = "PostgreSQL"
level = 85

[[extra.skills]]
name = "Go"
level = 80

[[extra.skills]]
name = "Node.js"
level = 85

[[extra.skills]]
name = "Python"
level = 75

[[extra.skills]]
name = "Terraform"
level = 85

[[extra.skills]]
name = "GitLab CI/CD"
level = 90

[[extra.skills]]
name = "Prometheus"
level = 85

[[extra.skills]]
name = "Grafana"
level = 85

# Education (Self-taught background)
[[extra.education]]
title = "Self-Taught Engineer"
institution = "Independent Learning & Real-World Experience"
start_date = "1997"
end_date = "Present"
description = "28+ years of continuous learning through hands-on projects, production systems, and deep technical exploration across the entire software engineering stack"

# Projects / Areas of Interest
[[extra.projects]]
title = "Cloud Infrastructure & Orchestration"
description = "Custom Kubernetes distributions, bare-metal hyperconverged platforms, multi-cloud hybrid architectures"
technologies = ["Kubernetes", "Proxmox", "ZFS", "InfiniBand", "WireGuard"]

[[extra.projects]]
title = "Observability & Monitoring"
description = "Enterprise-scale monitoring, alerting, and observability implementations"
technologies = ["Grafana", "Prometheus", "VictoriaMetrics", "NetData", "Jaeger", "ELK"]

[[extra.projects]]
title = "DevOps & CI/CD"
description = "Build pipelines, infrastructure-as-code, GitOps workflows, automated deployments"
technologies = ["GitLab CI/CD", "GitHub Actions", "Jenkins", "Terraform", "Ansible", "AWS CDK"]

[[extra.projects]]
title = "Systems Programming & Tooling"
description = "CLI tools, desktop applications, automation scripts, infrastructure utilities"
technologies = ["Go", "Rust", "Bash", "Node.js", "TypeScript"]

# Core Competencies (replacing certifications since this is self-taught)
[[extra.certifications]]
title = "Cloud Architecture & Infrastructure"
description = "AWS, GCP, Multi-cloud strategies, Infrastructure as Code"

[[extra.certifications]]
title = "Container Orchestration & Virtualization"
description = "Kubernetes, Docker, Proxmox, KVM, systemd, bootc"

[[extra.certifications]]
title = "Database Management & Performance"
description = "PostgreSQL, MySQL, SQLite, DuckDB, MongoDB"

[[extra.certifications]]
title = "Network Engineering"
description = "VPN, VLAN, BGP, Layer 2/3, WireGuard, ZeroTier, VyOS"

[[extra.certifications]]
title = "Security & Compliance"
description = "Vulnerability scanning, security hardening, IAM policies, financial industry standards"

# Languages (Programming/Scripting)
[[extra.languages]]
name = "Bash/Shell"
level = "Expert"
proficiency = 95

[[extra.languages]]
name = "JavaScript/TypeScript"
level = "Advanced"
proficiency = 85

[[extra.languages]]
name = "Go"
level = "Advanced"
proficiency = 80

[[extra.languages]]
name = "Python"
level = "Intermediate"
proficiency = 75

[[extra.languages]]
name = "Rust"
level = "Intermediate"
proficiency = 70

# Awards/Recognition (optional - can be commented out if not needed)
[[extra.awards]]
title = "Self-Taught Innovator"
description = "28+ years of independent learning and professional achievement"
